spring:
  application:
    name: FANTASTIC2-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/VaccinationDB1
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server.port: 8082